### ISSUE TITLE
Can not compile PyFx.hpp

### ISSUE THREAD

**Issue by luciddream-tsin** [Trentonom0r3/AETK#7]
when I compile the project, err I got:
```
ERROR	C2653	“pyfx”: is not class or namespace.	AETK	C:\Codes\CCPP\AETK\AETK\AEGP\Core\PyFx.cpp	8		

```

After I comments them, it compiled successfully.

**Comment by Trentonom0r3** [comment]
I need to add some clearer separation-- AETK won't compile unless its in a plugin, and PyFX is the same, and only used with a specific plugin setup!
